name: CD

on:
  workflow_dispatch:
  push:
    branches:
    - master
  pull_request:

env:
  DOCKER_BUILDKIT: "1"

jobs:
  build:
    name: Build Container Images
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-buildx-action@v2
    - uses: docker/login-action@v2
      if: ${{ github.event_name != 'pull_request' }}
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: "ghcr.io/j-brn/anti-anti-ananas.club"
        tags: |
          type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'master') }}
          
    - name: Build Dockerfile
      uses: docker/build-push-action@v4
      with:
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64
